# Generated by Django 6.0.6 on 2026-06-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_chamada', models.IntegerField()),
                ('nome', models.CharField(max_length=150)),
                ('ra', models.CharField(max_length=20)),
                ('digito_ra', models.CharField(max_length=5)),
                ('situacao', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=15)),
                ('status', models.CharField(choices=[('SALA', 'Na Sala'), ('FILA', 'Na Fila'), ('BANHEIRO', 'No Banheiro')], default='SALA', max_length=15)),
            ],
        ),
    ]
