# Generated by Django 6.0.6 on 2026-06-10 21:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_banheiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='data_entrada_fila',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RegistroBanheiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('hora_saida', models.DateTimeField(auto_now_add=True)),
                ('hora_retorno', models.DateTimeField(blank=True, null=True)),
                ('duracao_minutos', models.IntegerField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='controle_banheiro.aluno')),
            ],
            options={
                'db_table': 'registro_banheiro',
                'ordering': ['-hora_saida'],
            },
        ),
    ]
